- name: Install postgresql
  tags: [ apk, postgresql ]
  community.general.apk:
    name: "postgresql{{ postgresql_version }}"

- name: Ensure data dataset
  tags: [ zfs, postgresql ]
  when: zfs
  community.general.zfs:
    name: "{{ zfs_data_pool }}{{ postgresql_data_dir }}"
    state: present
    extra_zfs_properties:
      mountpoint: "{{ postgresql_data_dir }}"

- name: Ensure postgres ownership
  tags: [ postgresql ]
  ansible.builtin.file:
    dest: "{{ postgresql_data_dir }}"
    owner: postgres
    group: postgres
    mode: 'u=rwX,g=,o='
    recurse: yes

- name: Configure postgresql
  tags: [ postgresql ]
  ansible.builtin.lineinfile:
    dest: /etc/conf.d/postgresql
    state: "{{ 'present' if item.value else 'absent' }}"
    line: "{{ item.key }}=\"{{ item.value }}\""
    regex: "^\\s*{{ item.key }}\\s*="
  loop:
    - { key: conf_dir, value: "{{ postgresql_data_dir }}" }
    - { key: data_dir, value: "{{ postgresql_data_dir }}" }
    - { key: pg_version, value: "{{ postgresql_version }}" }

- name: Enable and start postgresql
  tags: [ postgresql ]
  ansible.builtin.service:
    name: postgresql
    enabled: yes
    state: started

