- name: Install argonone dependencies
  tags: apk
  community.general.apk:
    name: [ py3-smbus, py3-rpigpio ]

- name: Copy argonone script
  ansible.builtin.copy:
    dest: /usr/local/bin/argononed.py
    src: argononed.py
    mode: '755'

- name: Copy argonone config
  ansible.builtin.copy:
    dest: /etc/argononed.conf
    src: argononed.conf

- name: Copy argonone init script
  ansible.builtin.copy:
    dest: /etc/init.d/argononed
    src: argononed-init
    mode: '755'

- name: Enable and start argonone script
  ansible.builtin.service:
    name: argononed
    enabled: yes
    state: started
