- name: Jellyfin data dataset
  community.general.zfs:
    name: "{{ zfs_data_pool }}{{ data_dir }}"
    state: present
    extra_zfs_properties:
      mountpoint: "{{ data_dir }}"

- name: Jellyfin group
  ansible.builtin.group:
    name: jellyfin
    system: yes
  register: group

- name: Jellyfin user
  ansible.builtin.user:
    name: jellyfin
    group: jellyfin
    system: yes
    home: "{{ data_dir }}"
  register: user

- name: Jellyfin data folders
  ansible.builtin.file:
    dest: "{{ data_dir }}/{{ item }}"
    state: directory
    owner: jellyfin
    group: jellyfin
  loop:
    - cache
    - config

- name: Jellyfin container
  containers.podman.podman_container:
    name: jellyfin
    image: docker.io/jellyfin/jellyfin:latest
    restart_policy: always
    user: "{{ user.uid }}:{{ group.gid }}"
    cmd_args: --no-healthcheck # fuck systemd timers
    mount:
      - 'type=bind,source={{ data_dir }}/cache,destination=/cache'
      - 'type=bind,source={{ data_dir }}/config,destination=/config'
      - 'type=bind,source={{ media_dir }},destination=/media,ro=true'
    label:
      traefik.http.routers.jellyfin.rule: Host(`jellyfin.totoro.family`) 
      traefik.http.routers.jellyfin.entrypoints: websecure
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096
