- hosts: antigone
  become: yes
  roles:
    - role: alpine-base
    - role: alpine-physical
    - role: sway-desktop
    - role: alpine-podman
    - role: prometheus
      tags: [prometheus]
    - role: minio
      tags: [minio]
