#!/usr/bin/env ansible-playbook
- hosts: bydlenka
  roles:
    - role: alpine-base
      alpine_release: v3.18

    - role: user-ansible
    - role: user-julie
    - role: user-tereza

    - role: dhcpcd
    - role: alpine-physical

    - role: alpine-podman
      enable_podman_service: yes
      podman_users: [ julie ]

        #- role: zfsbootmenu
        #kernel_cmdline: "quiet intel_iommu=on vfio-pci.ids=1106:3483"
        #boot_partitions:
        #- /boot/efi0
        #- /boot/efi1

    - role: alpine-initramfs
      mkinitfs_features: base keymap kms nvme usb vfio zfs zfshost
      vfio_softdeps: [ xhci_hcd ]
      tags: [ haos ]

    - role: vlan-if
      vars:
        ifname: eth0.8
        vlan: 8
        raw_device: eth0

    - role: vlan-if
      vars:
        ifname: eth0.2
        vlan: 2
        raw_device: eth0
        inet_dhcp: true
        inet6_auto: true

    - role: samba
      tags: [ samba, servarr ]

    - role: haos-vm
      tags: [ haos ]

    - role: haos-backups
      tags: [ haos, haos-backups ]
      data_dir: /data/backups/haos

    - role: postgresql
      data_dir: /data/postgres15
      tags: [ postgres, haos ]

    - role: dnsmasq
      tags: [ dnsmasq ]

    - role: servarr
      zfs_data_pool: tank
      data_dir: /data/servarr
      tags: [ servarr ]

    - role: scrypted
      tags: [ scrypted ]

    - role: traefik
      tags: [ podman, servarr, traefik ]
    
