- hosts: bydlenka.totoro.family
  become: yes
  roles:
    - role: alpine-base
      alpine_release: v3.18

    - role: alpine-physical

    - role: alpine-podman
      enable_podman_service: yes
      podman_users: [ julie ]

        #- role: zfsbootmenu
        #kernel_cmdline: "quiet intel_iommu=on vfio-pci.ids=1106:3483"
        #boot_partitions:
        #- /boot/efi0
        #- /boot/efi1

    - role: alpine-initramfs
      mkinitfs_features: base keymap kms nvme usb vfio zfs zfshost
      vfio_softdeps: [ xhci_hcd ]
      tags: [ haos ]

    - role: alpine-samba
      shares:
        - name: Media
          path: /data/servarr/media
          valid users: '@wheel'
          write list: '@wheel'
        - name: Torrents
          path: /data/servarr/torrents
          valid users: '@wheel'
          write list: '@wheel'
      tags: [ samba, servarr ]

    - role: vlan-if
      ifname: eth0-things
      vlan: 8
      raw_device: eth0
      tags: [ haos ]

    - role: bridge-if
      ifname: br-things
      bridge_ports:
        - eth0-things
      tags: [ haos ]

    - role: qemu-bridge
      ifname: br-things
      tags: [ haos ]

    - role: postgresql
      data_dir: /data/postgres15
      tags: [ postgres, haos ]

    - role: qemu-vm
      user: root
      vmname: haos
      memory: 16G
      net0: bridge
      net0_br: br-things
      disk0_file: /data/vm/haos/disk0.img
      disk0_format: raw
      ovmf: yes
      ovmf_vars: /data/vm/haos/ovmf_vars.fd
      extra_args: "-device vfio-pci,host=02:00.0"
      shutdown_timeout: 180
      tags: [ haos ]

    - role: ssh-user
      user: tereza
      github_username: the-ress
      user_groups: [ wheel ]
      tags: [ tereza ]

    - role: split-dnsmasq
      interface: eth0
      tags: [ dnsmasq ]

    - role: servarr
      zfs_data_pool: tank
      data_dir: /data/servarr
      tags: [ servarr ]

    - role: traefik
      tags: [ podman, servarr, traefik ]
    
  tasks:
    - name: "Allow Tereza to ansible"
      ansible.posix.authorized_key:
        user: ansible
        key: "https://github.com/the-ress.keys"
      tags: [ ssh, tereza ]


