- hosts: bydlenka.totoro.family
  become: yes
  roles:
    - role: alpine-base
      alpine_release: v3.18

    - role: alpine-physical

    - role: alpine-podman
      enable_podman_service: yes
      podman_users: [ julie ]

        #- role: zfsbootmenu
        #kernel_cmdline: "quiet intel_iommu=on vfio-pci.ids=1106:3483"
        #boot_partitions:
        #- /boot/efi0
        #- /boot/efi1

    - role: alpine-initramfs
      mkinitfs_features: base keymap kms nvme usb vfio zfs zfshost
      vfio_softdeps: [ xhci_hcd ]

    - role: alpine-samba
      shares:
        - name: Downloads
          path: /data/downloads
          valid users: '@downloads'

    - role: vlan-if
      ifname: eth0-things
      vlan: 8
      raw_device: eth0

    - role: bridge-if
      ifname: br-things
      bridge_ports:
        - eth0-things

    - role: qemu-bridge
      ifname: br-things

    - role: postgresql
      data_dir: /data/postgres15

    - role: qemu-vm
      user: root
      vmname: haos
      memory: 16G
      net0: bridge
      net0_br: br-things
      disk0_file: /data/vm/haos/disk0.img
      disk0_format: raw
      ovmf: yes
      ovmf_vars: /data/vm/haos/ovmf_vars.fd
      extra_args: "-device vfio-pci,host=02:00.0"

    - role: ssh-user
      user: tereza
      github_username: the-ress
      user_groups: [ wheel ]

    - role: split-dnsmasq
      interface: eth0

    - role: jellyfin
      data_dir: /data/jellyfin
      media_dir: /data/downloads
      tags: [ jellyfin, podman, traefik ]

    - role: qbittorrent
      data_dir: /data/qbittorrent
      tags: [ qbittorrent, podman, traefik ]

    - role: traefik
      tags: [ podman, traefik ]
    
