#!/usr/bin/env ansible-playbook
- hosts: backup_sources
  roles:
    - role: backup-push-source

- hosts: backup_targets
  tasks:
    - name: Add users
      loop: [user-ansible, user-julie, user-tereza]
      ansible.builtin.include_role:
        name: "{{ item }}"

    - name: Allow nopass doas
      ansible.builtin.include_role:
        name: doas-entry
      vars:
        line: permit nopass :wheel

    - name: Create backup source on target
      ansible.builtin.include_role: 
        name: backup-push-target
      vars:
        source_name: "{{ item }}"
        ssh_publickey: "{{ hostvars[item].backup_publickey }}"
      loop: "{{ groups.backup_sources }}"

