- hosts: prusheenmon
  become: yes
  roles:
    - role: ansible-base
    - role: dhcpcd
    - role: rpi-bootloader
    - role: prusamon
    - role: user-ansible
    - role: user-julie
    - role: user-tereza
