- hosts: prusheenmon
  become: yes
  roles:
    - role: rpi-bootloader
    - role: prusamon
    - role: user-ansible
    - role: ssh-user
      user: tereza
      groups: wheel
      github_usernames: [ the-ress ]

