#!/usr/bin/env ansible-playbook
- hosts: backup-ns
  roles:
    - alpine-physical
    - rpi-argonone
- hosts: totoro_dns
  roles:
    - role: alpine-base
    - role: dhcpcd
    - role: dnsmasq
    - role: user-ansible
    - role: user-julie
    - role: user-tereza
