- name: Install podman and fuse-overlayfs
  tags: [ apk, podman ]
  community.general.apk:
    name: [ podman, fuse, fuse-overlayfs ]
    state: present

- name: Configure unified cgroup mode
  tags: [ podman ]
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    line: rc_cgroup_mode="unified"
    regex: "^rc_group_mode="

- name: Enable needed services
  tags: [ podman ]
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop: [ cgroups, modules ]

- name: Ensure subuid and subgid
  tags: [ podman ]
  include_role:
    name: podman-user
  loop: "{{ podman_users }}"
  loop_control:
    loop_var: podman_user

- name: Ensure ZFS dataset
  tags: [ podman, zfs ]
  when: zfs_root_dataset | default(false)
  community.general.zfs:
    name: "{{ zfs_root_dataset }}/var/lib/containers"
    state: present

- name: Ensure modules
  tags: [ podman ]
  ansible.builtin.include_role:
    name: alpine-kernel-module
  loop: [ fuse, tun ]
  loop_control: { loop_var: module }

- name: Enable service
  tags: [ podman ]
  when: enable_podman_service
  ansible.builtin.service:
    name: podman
    enabled: yes
    state: started

