- name: Create /etc/network/interfaces.d
  ansible.builtin.file:
    path: /etc/network/interfaces.d
    state: directory

- name: Source /etc/network/interfaces.d
  ansible.builtin.lineinfile:
    path: /etc/network/interfaces
    line: 'source-directory /etc/network/interfaces.d'

- name: Ensure @testing repo
  tags: apk
  ansible.builtin.lineinfile:
    dest: /etc/apk/repositories
    line: "@testing {{ alpine_mirror }}/edge/testing"
    regexp: "^@testing\\s"
    insertafter: EOF

- name: Ensure extra repos
  tags: apk
  loop: "{{ apk_extra_repos }}"
  ansible.builtin.lineinfile:
    dest: /etc/apk/repositories
    line: "{{ item }}"
    insertafter: EOF

- name: Install packages
  tags: apk
  community.general.apk:
    update_cache: yes
    name:
      - curl
      - doas
      - iputils # ping without root

- name: Install ZFS packages
  tags: [ apk, zfs ]
  when: zfs
  community.general.apk:
    name: zfs-auto-snapshot

- name: Set timezone
  ansible.builtin.command:
    cmd: "setup-timezone -i {{ timezone }}"
    creates: /etc/localtime

- name: Clear MOTD
  ansible.builtin.copy:
    dest: /etc/motd
    content: ""

- name: Disable root SSH login 
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'PermitRootLogin no'
    regex: '^#?PermitRootLogin'
    insertbefore: BOF # first one wins with sshd_config
  tags: [ ssh ]

- name: Disable SSH password authentication
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'PasswordAuthentication no'
    regex: '^#?PasswordAuthentication'
    insertbefore: BOF # first one wins with sshd_config
  tags: [ ssh ]
