- name: Ensure @testing repo
  tags: apk
  ansible.builtin.lineinfile:
    dest: /etc/apk/repositories
    line: "@testing {{ alpine_mirror }}/edge/testing"
    regexp: "^@testing\\s"
    insertafter: EOF

- name: Ensure extra repos
  tags: apk
  loop: "{{ apk_extra_repos }}"
  ansible.builtin.lineinfile:
    dest: /etc/apk/repositories
    line: "{{ item }}"
    insertafter: EOF

- name: Install packages
  tags: apk
  community.general.apk:
    update_cache: yes
    name:
      - curl
      - doas
      - iputils # ping without root

- name: Set timezone
  ansible.builtin.command:
    cmd: "setup-timezone -i {{ timezone }}"
    creates: /etc/localtime

- name: Enable and start syslog
  ansible.builtin.service:
    name: syslog
    enabled: yes
    state: started

- name: Clear MOTD
  ansible.builtin.copy:
    dest: /etc/motd
    content: ""

- ansible.builtin.import_tasks: network.yaml
  tags: [ network ]

- ansible.builtin.import_tasks: sshd.yaml
  tags: [ sshd ]

- name: Timeout login shells
  ansible.builtin.copy:
    dest: /etc/profile.d/julie-tmout.sh
    content: |
      TMOUT={{ shell_tmout }}
      readonly TMOUT
