- ansible.builtin.import_tasks: apk.yaml
  tags: apk

- name: Set timezone
  ansible.builtin.command:
    cmd: "setup-timezone -i {{ timezone }}"
    creates: /etc/localtime

- name: Enable and start syslog
  when: syslog_enabled
  tags: syslog
  ansible.builtin.service:
    name: syslog
    enabled: yes
    state: started

- name: Clear MOTD
  ansible.builtin.copy:
    dest: /etc/motd
    content: ""

- ansible.builtin.import_tasks: network.yaml
  tags: network 

