- name: Create /etc/network/interfaces.d
  tags: network
  ansible.builtin.file:
    path: /etc/network/interfaces.d
    state: directory

- name: Create /etc/network/interfaces
  tags: network
  ansible.builtin.copy:
    dest: /etc/network/interfaces
    src: interfaces

- name: Configure auto interfaces
  tags: network
  loop: "{{ net_ifaces }}"
  ansible.builtin.template:
    dest: "/etc/network/interfaces.d/{{ item.name }}"
    src: auto_iface.j2
