- name: Ensure device tree overlays
  ansible.builtin.lineinfile:
    dest: /boot/usercfg.txt
    line: "dtoverlay={{ item }}"
  loop: "{{ usercfg_dtoverlays }}"

- name: Ensure bootloader configuration
  ansible.builtin.lineinfile:
    dest: /boot/usercfg.txt
    state: "{{ 'present' if item.value else 'absent' }}"
    line: "{{ item.key }}={{ item.value }}"
    regex: "^\\s*{{ item.key }}\\s*="
  loop: "{{ usercfg_vars | dict2items }}"
    
