- name: Ensure alpine-sdk package
  community.general.apk:
    name: alpine-sdk
    state: present

- name: Add alpine_sdk_users to abuild group
  ansible.builtin.user:
    name: "{{ item }}"
    append: yes
    groups: abuild
  loop: "{{ alpine_sdk_users }}"

- name: Ensure /var/cache/distfiles
  ansible.builtin.file:
    dest: /var/cache/distfiles
    state: directory
    group: abuild
    mode: "g+w"
