- name: Install flatpak
  tags: flatpak
  community.general.apk:
    name: flatpak

- name: Add flathub
  tags: flatpak
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
