- name: Enable I2C
  ansible.builtin.include_role:
    name: rpi-bootloader
  vars:
    usercfg_vars:
      dtparam: i2c_arm=on

- name: Modprobe I2C
  ansible.builtin.include_role:
    name: alpine-kernel-module
  vars:
    module: '{{ item }}'
  loop:
    - i2c-bcm2708
    - i2c-dev

- name: Install argonone dependencies
  tags: apk
  community.general.apk:
    update_cache: yes
    name: [ py3-smbus, py3-rpigpio ]

- name: Copy argonone script
  ansible.builtin.copy:
    dest: /usr/local/bin/argononed.py
    src: argononed.py
    mode: '755'

- name: Copy argonone config
  ansible.builtin.copy:
    dest: /etc/argononed.conf
    src: argononed.conf

- name: Copy argonone init script
  ansible.builtin.copy:
    dest: /etc/init.d/argononed
    src: argononed-init
    mode: '755'

- name: "Enable and start argonone script"
  ansible.builtin.service:
    name: "argononed"
    enabled: yes
    state: started
