- name: Install packages
  community.general.apk:
    name:
      - dosfstools
      - e2fsprogs
      - efibootmgr
      - eudev
      - eudev-netifnames
      - font-terminus
      - lm-sensors
      - lm-sensors-detect
      - lm-sensors-fancontrol
      - lsblk
      - mingetty
      - openntpd
      - openssh
      - pciutils
      - usbutils
      - sfdisk

- name: Setup udev
  tags: [udev]
  ansible.builtin.command:
    cmd: setup-devd -C udev
    creates: /etc/runlevels/sysinit/udev

- name: Use mingetty
  tags: [inittab]
  ansible.builtin.template:
    dest: /etc/inittab
    src: inittab

- name: Enable and start syslog
  ansible.builtin.service:
    name: syslog
    enabled: yes
    state: started

- name: Allow wheel to reboot and poweroff
  ansible.builtin.include_role:
    name: doas-entry
  vars:
    line: "permit nopass :wheel cmd {{ item }}"
  loop: [ poweroff, reboot ]

- ansible.builtin.import_role:
    name: backup-apk-commit-hook
  tags: [ apk, zfs, autobackup ]
  when: zfs | default(false)

- ansible.builtin.import_tasks: bluetooth.yaml
  when: bluetooth | default(false)
  tags: [ bluetooth ]

- ansible.builtin.import_tasks: chrony.yaml
  tags: [ chrony ]

- ansible.builtin.import_tasks: consolefont.yaml
  tags: [ consolefont ]
  when: consolefont

- ansible.builtin.import_tasks: zfs.yaml
  tags: [ zfs ]
  when: zfs

- ansible.builtin.import_tasks: nct6683.yaml
  when: force_nct6683
