- name: Install zfs packages
  community.general.apk:
    name: [ zfs-udev, zfs-lts, zfs ]

- name: Enable zfs services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
  loop: [ zfs-import, zfs-load-key, zfs-mount ]
