- name: "Create user {{ source_name }}"
  ansible.builtin.user:
    name: "{{ source_name }}"
    system: yes
    password: '*'

- name: "Authorize {{ source_name }} public key"
  ansible.posix.authorized_key:
    user: "{{ source_name }}"
    key: "{{ ssh_publickey }}"
  tags: [ ssh ]

- name: "Create dataset {{ zfs_backups_dataset }}/{{ source_name }}"
  community.general.zfs:
    name: "{{ zfs_backups_dataset }}/{{ source_name }}"
    state: present

- name: "Configure ZFS permissions for {{ source_name }}"
  community.general.zfs_delegate_admin:
    name: "{{ zfs_backups_dataset }}/{{ source_name }}"
    permissions: 
      - acltype
      - canmount
      - compression
      - create
      - destroy
      - dnodesize
      - hold
      - mount
      - mountpoint
      - readonly
      - receive
      - refreservation
      - release
      - rollback
      - xattr
    users: "{{ source_name }}"
