- name: Install packages
  tags: [apk]
  when: ansible_distribution == 'Alpine'
  community.general.apk:
    name:
      - chezmoi
      - curl
      - doas
      - docs
      - delta
      - drill
      - "{{ eza_or_exa }}"
      - fzf
      - git
      - htop
      - iputils # ping without root
      - jq
      - less
      - man-pages
      - mandoc
      - neovim
      - ripgrep
      - rsync
      - shadow
      - starship
      - strace
      - tcpdump
      - tzdata
      - zsh


