- name: Install packages
  tags: [ sway ]
  community.general.apk:
    name: 
      - chromium
      - font-awesome
      - font-cascadia-code-nerd
      - font-dejavu
      - font-inconsolata
      - font-noto
      - font-noto-cjk 
      - font-noto-emoji
      - font-noto-extra
      - gvfs-smb
      - mako
      - libfido2
      - swaybg
      - swayidle
      - swaylock
      - thunar
      - waybar
      - wlvncc@testing
      - wvkbd

- name: Add users to plugdev group
  tags: [ sway ]
  ansible.builtin.user:
    name: "{{ item }}"
    append: yes
    groups: [ plugdev ]
  loop: "{{ sway_users }}"

- name: Run pipewire-launcher
  tags: [ sway, pipewire ]
  ansible.builtin.copy:
    dest: /etc/sway/config.d/pipewire
    content: exec /usr/libexec/pipewire-launcher
