dependencies:
  - role: bridge-if
    vars:
      ifname: br0
      bridge_ports:
        - enp5s0

  - role: qemu-bridge
    vars:
      ifname: br0

  - role: qemu-vm
    vars:
      user: root
      vmname: haos
      memory: 16G
      net0: bridge
      net0_br: br0
      disk0_file: /data/vm/haos/disk0.img
      disk0_format: raw
      ovmf: yes
      ovmf_vars: /data/vm/haos/ovmf_vars.fd
      extra_args: "-device vfio-pci,host=02:00.0"
      shutdown_timeout: 180
      tags: [ haos ]


