- name: Install prometheus
  tags: [ apk ]
  community.general.apk:
    name: prometheus

- name: Configure prometheus
  ansible.builtin.template:
    dest: /etc/prometheus/prometheus.yml
    src: prometheus.yml.j2

- name: Enable and start prometheus
  ansible.builtin.service:
    name: prometheus
    enabled: yes
    state: started


