#!/bin/sh
set -e

if [ `id -u` != 0 ]; then
  echo must be root >&2
  exit 1
fi

if [ `uname` = "FreeBSD" ]; then
  platform=freebsd
  doasconf=/usr/local/etc/doas.conf
elif command -v apk > /dev/null; then
  platform=alpine
  doasconf=/etc/doas.d/doas.conf
else
  echo unknown OS >&2
  exit 1
fi

packages_alpine() {
  apk add curl doas openssh python3 
}

user_alpine() {
  local username=$1 group=$2 uid=$3
  adduser -D -G "$group" -u "$uid" "$username" 
  # unlock the user, but don't allow password login
  echo "$username:*" | chpasswd -e 
}

sshd_alpine() {
  rc-update add sshd
  rc-service sshd start
}

packages_freebsd() {
  pkg install python311 doas curl
}

user_freebsd() {
  pw useradd -m -n "$1" -u "$3" -g "$2" -w no
}

sshd_freebsd() {
  if [ `sysrc -n sshd_enable` != "YES" ]; then
    sysrc sshd_enable=YES
  fi
  if ! service sshd status > /dev/null; then
    service sshd start
  fi
}

packages_$platform
sshd_$platform

if ! grep -Eq "^ansible:" /etc/passwd; then
  user_$platform ansible wheel 2000
fi

cat > "$doasconf" <<EOF 
permit persist :wheel
permit nopass ansible
EOF

su ansible -c '
  set -ex
  mkdir -p -m 700 "$HOME/.ssh";
  curl --silent https://github.com/juliekoubova.keys -o "$HOME/.ssh/authorized_keys";
  chmod 644 "$HOME/.ssh/authorized_keys"'

