#!/bin/sh

: ${ALPINE_MIRROR:=https://dl-cdn.alpinelinux.org/alpine}
: ${ALPINE_REPOS:=main community}

repos_file="/etc/apk/repositories"

grep -Eq ^https:// "${repos_file}" && exit

ALPINE_REL="v$( \
  cat /etc/os-release \
  | grep -E ^VERSION_ID= \
  | cut -d= -f2 \
  | cut -d. -f1,2 \
  )"

truncate -s 0 "${repos_file}"
for repo in ${ALPINE_REPOS}; do
  echo "${ALPINE_MIRROR}/${ALPINE_REL}/${repo}" >> "${repos_file}"
done
