- name: "Create user {{ user }}"
  ansible.builtin.user:
    name: "{{ user }}"
    shell: "{{ shell | default(omit) }}"
    group: "{{ user_group | default(omit) }}"
    uid: "{{ uid | default(omit) }}"
    password: "*"
    update_password: on_create
    system: "{{ system | default(omit) }}"
  tags: [ ssh ]

- name: "Download authorized_keys from GitHub for user {{ user }}"
  ansible.posix.authorized_key:
    user: "{{ user }}"
    key: "https://github.com/{{ item }}.keys"
  loop: "{{ github_usernames }}"
  tags: [ ssh ]

