- name: "Create user {{ user }}"
  ansible.builtin.user:
    name: "{{ user }}"
    shell: "{{ shell | default(omit) }}"
    group: "{{ user_group | default(omit) }}"
    groups: "{{ user_groups | default(omit) }}"
    append: "{{ (user_groups | default([]) | length) > 0 }}"
    uid: "{{ uid | default(omit) }}"
    password: "*"
    update_password: on_create
    system: "{{ system | default(omit) }}"
  tags: [ ssh ]

- name: "Add authorized keys for user {{ user }}"
  when: "ssh_keys | default('')"
  ansible.posix.authorized_key:
    user: "{{ user }}"
    key: "{{ ssh_keys }}"
  tags: [ ssh ]

