- name: Install MinIO
  tags: [ apk ]
  community.general.apk:
    name: [ minio, minio-client ]

- name: MinIO dataset
  tags: [ zfs ]
  when: zfs and (minio_data_dir | default(false))
  community.general.zfs:
    name: "{{ zfs_data_pool }}{{ minio_data_dir }}"
    state: present
    extra_zfs_properties:
      mountpoint: "{{ minio_data_dir }}"

- name: Configure MinIO
  ansible.builtin.template:
    dest: /etc/conf.d/minio
    src: confd.j2
    owner: root
    group: root
    mode: '750'

- name: Enable and start MinIO
  ansible.builtin.service:
    name: minio
    enabled: yes
    state: started

- name: Get mcli alias
  register: mcli_alias
  changed_when: false
  failed_when: false
  ansible.builtin.shell: >
    mcli alias ls "{{ minio_alias }}" 

- name: Set mcli alias
  when: mcli_alias.rc != 0
  no_log: true
  ansible.builtin.shell: >
    mcli alias set "{{ minio_alias }}" \
      "http://{{ minio_address }}" \
      "{{ minio_root_user }}" \
      "{{ minio_root_password }}"

- name: Create MinIO users
  loop: "{{ minio_users }}"
  no_log: true
  ansible.builtin.include_tasks: user.yaml

- name: Create MinIO buckets
  loop: "{{ minio_buckets }}"
  ansible.builtin.include_tasks: bucket.yaml
