argument_specs:
  main:
    options:
      extra_args:
        type: str
        default: ''
      vmname:
        required: yes
      cpus:
        type: int
        default: 2
      memory:
        type: str
        default: 2G
      net0:
        type: str
      net0_br:
        type: str
      ovmf:
        type: bool
        default: yes
      ovmf_vars:
        type: path
        required: yes
      disk0_file: 
        type: path 
        required: yes
      disk0_format:
        type: str
        choices: [ qcow2, raw ]
        required: yes
      user:
        type: str
        default: ''
