- name: Install dnsmasq
  community.general.apk:
    name: dnsmasq-dnssec

- name: Configure dnsmasq
  ansible.builtin.template:
    dest: /etc/dnsmasq.conf
    src: dnsmasq.conf.j2
  register: config

- name: Configure dnsmasq service
  ansible.builtin.template:
    dest: /etc/conf.d/dnsmasq
    src: confd.j2
  register: service_config

- name: Stop dnsmasq
  when: config.changed or service_config.changed
  ansible.builtin.service:
    name: dnsmasq
    state: stopped

- name: Start and enable dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: yes
