- name: Setup udev rules
  tags: [ sway, udev ]
  notify: 'reload udev rules'
  ansible.builtin.copy:
    dest: /etc/udev/rules.d/julie-backlight.rules
    src: julie-backlight.rules

- name: Install packages
  tags: [ sway ]
  community.general.apk:
    name: 
      - capitaine-cursors
      - dbus
      - foot
      - font-dejavu
      - font-inconsolata
      - font-noto
      - font-noto-cjk 
      - font-noto-emoji
      - font-noto-extra
      - mesa-dri-gallium
      - mesa-va-gallium
      - sway
      - seatd
      - wl-clipboard
      - wlr-randr
      - xwayland
      - zzz

- name: "Start services"
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - dbus
    - seatd

- name: Add users to groups
  ansible.builtin.user:
    name: "{{ item }}"
    append: yes
    groups: [ audio, input, seat, video ]
  loop: "{{ sway_users }}"

- name: Install scripts
  ansible.builtin.copy:
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    src: "{{ item }}"
  loop:
    - swayzzz
    - zzz-if-no-ssh

- name: Allow doas scripts without password
  tags: [ doas ]
  ansible.builtin.lineinfile:
    dest: /etc/doas.conf
    line: "permit nopass :wheel cmd zzz-if-no-ssh"

- name: Suspend when power button pressed
  tags: [ sway ]
  ansible.builtin.copy:
    dest: /etc/acpi/PWRF/00000080
    mode: 0755
    content: |
      #!/bin/sh
      exec swayzzz

- name: Create /etc/sway/config.d
  tags: [ sway ]
  ansible.builtin.file:
    dest: /etc/sway/config.d
    state: directory
